[package]
name = "lumd"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = {version = "0.30.1", features = ["user"]}
thiserror = "1.0"
slog = "2.7.0"
slog-term = "2.9.0"
slog-async = "2.7.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
signal-hook = "0.3.17"