[package]
name = "lumctl"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = {version = "0.30.1", features = ["user"]}
dirs = "5.0"
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
