[build]
rustflags = ["-C", "target-feature=-crt-static"]

[target.x86_64-unknown-linux-gnu]
linker = "gcc"
rustflags = ["-C", "target-feature=-crt-static", "-C", "link-arg=-fuse-ld=gold"]

[target.aarch64-unknown-linux-gnu]
linker = "gcc"
rustflags = ["-C", "target-feature=-crt-static", "-C", "link-arg=-fuse-ld=gold"]
